Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Discounts;
using Nop.Core.Domain.Media;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Vendors;
using Nop.Core.Http;
using Nop.Core.Infrastructure;
using Nop.Services.Catalog;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Discounts;
using Nop.Services.ExportImport;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Shipping;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;
using Nop.Web.Framework.Mvc.ModelBinding;
using Nop.Web.Framework.Validators;

namespace Nop.Web.Areas.Admin.Controllers;

public partial class ProductController : BaseAdminController
{
    #region Fields

    protected readonly IAclService _aclService;
    protected readonly IBackInStockSubscriptionService _backInStockSubscriptionService;
    protected readonly ICategoryService _categoryService;
    protected readonly ICopyProductService _copyProductService;
    protected readonly ICustomerActivityService _customerActivityService;
    protected readonly ICustomerService _customerService;
    protected readonly IDiscountService _discountService;
    protected readonly IDownloadService _downloadService;
    protected readonly IExportManager _exportManager;
    protected readonly IGenericAttributeService _genericAttributeService;
    protected readonly IHttpClientFactory _httpClientFactory;
    protected readonly IImportManager _importManager;
    protected readonly ILanguageService _languageService;
    protected readonly ILocalizationService _localizationService;
    protected readonly ILocalizedEntityService _localizedEntityService;
    protected readonly IManufacturerService _manufacturerService;
    protected readonly INopFileProvider _fileProvider;
    protected readonly INotificationService _notificationService;
    protected readonly IPdfService _pdfService;
    protected readonly IPermissionService _permissionService;
    protected readonly IPictureService _pictureService;
    protected readonly IProductAttributeFormatter _productAttributeFormatter;
    protected readonly IProductAttributeParser _productAttributeParser;
    protected readonly IProductAttributeService _productAttributeService;
    protected readonly IProductModelFactory _productModelFactory;
    protected readonly IProductService _productService;
    protected readonly IProductTagService _productTagService;
    protected readonly ISettingService _settingService;
    protected readonly IShippingService _shippingService;
    protected readonly IShoppingCartService _shoppingCartService;
    protected readonly ISpecificationAttributeService _specificationAttributeService;
    protected readonly IStoreContext _storeContext;
    protected readonly IUrlRecordService _urlRecordService;
    protected readonly IVideoService _videoService;
    protected readonly IWebHelper _webHelper;
    protected readonly IWorkContext _workContext;
    protected readonly VendorSettings _vendorSettings;
    private static readonly char[] _separator = [','];

    #endregion

    #region Ctor

    public ProductController(IAclService aclService,
        IBackInStockSubscriptionService backInStockSubscriptionService,
        ICategoryService categoryService,
        ICopyProductService copyProductService,
        ICustomerActivityService customerActivityService,
        ICustomerService customerService,
        IDiscountService discountService,
        IDownloadService downloadService,
        IExportManager exportManager,
        IGenericAttributeService genericAttributeService,
        IHttpClientFactory httpClientFactory,
        IImportManager importManager,
        ILanguageService languageService,
        ILocalizationService localizationService,
        ILocalizedEntityService localizedEntityService,
        IManufacturerService manufacturerService,
        INopFileProvider fileProvider,
        INotificationService notificationService,
        IPdfService pdfService,
        IPermissionService permissionService,
        IPictureService pictureService,
        IProductAttributeFormatter productAttributeFormatter,
        IProductAttributeParser productAttributeParser,
        IProductAttributeService productAttributeService,
        IProductModelFactory productModelFactory,
        IProductService productService,
        IProductTagService productTagService,
        ISettingService settingService,
        IShippingService shippingService,
        IShoppingCartService shoppingCartService,
        ISpecificationAttributeService specificationAttributeService,
        IStoreContext storeContext,
        IUrlRecordService urlRecordService,
        IVideoService videoService,
        IWebHelper webHelper,
        IWorkContext workContext,
        VendorSettings vendorSettings)
    {
        _aclService = aclService;
        _backInStockSubscriptionService = backInStockSubscriptionService;
        _categoryService = categoryService;
        _copyProductService = copyProductService;
        _customerActivityService = customerActivityService;
        _customerService = customerService;
        _discountService = discountService;
        _downloadService = downloadService;
        _exportManager = exportManager;
        _genericAttributeService = genericAttributeService;
        _httpClientFactory = httpClientFactory;
        _importManager = importManager;
        _languageService = languageService;
        _localizationService = localizationService;
        _localizedEntityService = localizedEntityService;
        _manufacturerService = manufacturerService;
        _fileProvider = fileProvider;
        _notificationService = notificationService;
        _pdfService = pdfService;
        _permissionService = permissionService;
        _pictureService = pictureService;
        _productAttributeFormatter = productAttributeFormatter;
        _productAttributeParser = productAttributeParser;
        _productAttributeService = productAttributeService;
        _productModelFactory = productModelFactory;
        _productService = productService;
        _productTagService = productTagService;
        _settingService = settingService;
        _shippingService = shippingService;
        _shoppingCartService = shoppingCartService;
        _specificationAttributeService = specificationAttributeService;
        _storeContext = storeContext;
        _urlRecordService = urlRecordService;
        _videoService = videoService;
        _webHelper = webHelper;
        _workContext = workContext;
        _vendorSettings = vendorSettings;
    }

    #endregion

    #region Utilities

    protected virtual async Task UpdateLocalesAsync(Product product, ProductModel model)
    {
        foreach (var localized in model.Locales)
        {
            await _localizedEntityService.SaveLocalizedValueAsync(product,
                x => x.Name,
                localized.Name,
                localized.LanguageId);
            await _localizedEntityService.SaveLocalizedValueAsync(product,
                x => x.ShortDescription,
                localized.ShortDescription,
                localized.LanguageId);
            await _localizedEntityService.SaveLocalizedValueAsync(product,
                x => x.FullDescription,
                localized.FullDescription,
                localized.LanguageId);
            await _localizedEntityService.SaveLocalizedValueAsync(product,
                x => x.MetaKeywords,
                localized.MetaKeywords,
                localized.LanguageId);
            await _localizedEntityService.SaveLocalizedValueAsync(product,
                x => x.MetaDescription,
                localized.MetaDescription,
                localized.LanguageId);
            await _localizedEntityService.SaveLocalizedValueAsync(product,
                x => x.MetaTitle,
                localized.MetaTitle,
                localized.LanguageId);

            //search engine name
            var seName = await _urlRecordService.ValidateSeNameAsync(product, localized.SeName, localized.Name, false);
            await _urlRecordService.SaveSlugAsync(product, seName, localized.LanguageId);
        }
    }

    protected virtual async Task UpdateLocalesAsync(ProductTag productTag, ProductTagModel model)
    {
        foreach (var localized in model.Locales)
        {
            await _localizedEntityService.SaveLocalizedValueAsync(productTag,
                x => x.Name,
                localized.Name,
                localized.LanguageId);

            var seName = await _urlRecordService.ValidateSeNameAsync(productTag, string.Empty, localized.Name, false);
            await _urlRecordService.SaveSlugAsync(productTag, seName, localized.LanguageId);
        }
    }

    protected virtual async Task UpdateLocalesAsync(ProductAttributeMapping pam, ProductAttributeMappingModel model)
    {
        foreach (var localized in model.Locales)
        {
            await _localizedEntityService.SaveLocalizedValueAsync(pam,
                x => x.TextPrompt,
                localized.TextPrompt,
                localized.LanguageId);
            await _localizedEntityService.SaveLocalizedValueAsync(pam,
                x => x.DefaultValue,
                localized.DefaultValue,
                localized.LanguageId);
        }
    }

    protected virtual async Task UpdateLocalesAsync(ProductAttributeValue pav, ProductAttributeValueModel model)
    {
        foreach (var localized in model.Locales)
        {

Presentation/Nop.Web/Areas/Admin/Views/Product/ProductAttributeMappingEdit.cshtml
@model ProductAttributeMappingModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Products.ProductAttributes.Attributes.EditAttributeDetails").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Products");
}

<form asp-controller="Product" asp-action="ProductAttributeMappingEdit" method="post" id="productattribute-form">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Products.ProductAttributes.Attributes.EditAttributeDetails")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="Edit" asp-route-id="@Model.ProductId">@T("Admin.Catalog.Products.ProductAttributes.Attributes.BackToProduct")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="productattribute-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ProductAttributeMappingDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateProductAttributeMapping", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-action="ProductAttributeMappingDelete" asp-button-id="productattribute-delete" />

Presentation/Nop.Web/Areas/Admin/Views/Product/ProductAttributeValueCreatePopup.cshtml
@model ProductAttributeValueModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.PageTitle = T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew").Text;
}
<form asp-controller="Product" asp-action="ProductAttributeValueCreatePopup"
      asp-route-productAttributeMappingId="@Context.Request.Query["productAttributeMappingId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew")
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ProductAttributeValueDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateProductAttributeValue", Model)
</form>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.CrossSellsProducts.cshtml
@model ProductModel
<div class="card-body">
    <p>
        @T("Admin.Catalog.Products.CrossSells.Hint")
    </p>
    @if (Model.Id > 0)
    {
    <div class="card card-default">

        <div class="card-body">
            @await Html.PartialAsync("Table", new DataTablesModel
            {
                Name = "crosssellproducts-grid",
                UrlRead = new DataUrl("CrossSellProductList", "Product", new RouteValueDictionary { [nameof(Model.CrossSellProductSearchModel.ProductId)] = Model.CrossSellProductSearchModel.ProductId }),
                UrlDelete = new DataUrl("CrossSellProductDelete", "Product", null),
                Length = Model.CrossSellProductSearchModel.PageSize,
                LengthMenu = Model.CrossSellProductSearchModel.AvailablePageSizes,
                ColumnCollection = new List<ColumnProperty>
                {
                    new ColumnProperty(nameof(CrossSellProductModel.Product2Name))
                    {
                        Title = T("Admin.Catalog.Products.CrossSells.Fields.Product").Text,
                        Render = new RenderCustom("renderColumnCrossSellProductName")
                    },
                    new ColumnProperty(nameof(CrossSellProductModel.Id))
                    {
                        Title = T("Admin.Common.Delete").Text,
                        Width = "100",
                        Render = new RenderButtonRemove(T("Admin.Common.Delete").Text),
                        ClassName = NopColumnClassDefaults.Button
                    }
                }
            })
            <script asp-location="Footer">
                function renderColumnCrossSellProductName(data, type, row, meta) {
                    var textRenderer = $.fn.dataTable.render.text().display;
                    return '<a href="@Url.Content("~/Admin/Product/Edit/")' + row.ProductId2 + '">' + textRenderer(row.Product2Name) + '</a>';
                }
            </script>
        </div>
        <div class="card-footer">
            <button type="submit" id="btnAddNewCrossSellProduct" onclick="javascript:OpenWindow('@(Url.Action("CrossSellProductAddPopup", "Product", new {productId = Model.Id, btnId = "btnRefreshCrossSellProducts", formId = "product-form"}))', 800, 800, true); return false;" class="btn btn-primary">
                @T("Admin.Catalog.Products.CrossSells.AddNew")
            </button>
            <button type="submit" id="btnRefreshCrossSellProducts" style="display: none"></button>
            <script>
                $(function() {
                    $('#btnRefreshCrossSellProducts').click(function () {
                        //refresh grid
                        updateTable('#crosssellproducts-grid');

                        //return false to don't reload a page
                        return false;
                    });
                });
            </script>
        </div>
    </div>
    }
    else
    {
        <div class="card card-default">
            <div class="card-body">
                @T("Admin.Catalog.Products.CrossSells.SaveBeforeEdit")
            </div>
        </div>
    }
</div>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.GiftCard.cshtml
@model ProductModel

@using Nop.Core.Domain.Catalog;
@using Nop.Services

 <div class="card-body">
        <div class="form-group row">
            <div class="col-md-3">
                <nop-label asp-for="IsGiftCard" />
            </div>
            <div class="col-md-9">
                <nop-editor asp-for="IsGiftCard" />
                <span asp-validation-for="IsGiftCard"></span>
            </div>
        </div>
        <nop-nested-setting asp-for="IsGiftCard">
            <div class="form-group row">
                <div class="col-md-3">
                    <nop-label asp-for="GiftCardTypeId" />
                </div>
                <div class="col-md-9">
                    <nop-select asp-for="GiftCardTypeId" asp-items="@(await ((GiftCardType)Model.GiftCardTypeId).ToSelectListAsync())" />
                    <span asp-validation-for="GiftCardTypeId"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-3">
                    <nop-label asp-for="OverriddenGiftCardAmount" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="OverriddenGiftCardAmount" />
                    <span asp-validation-for="OverriddenGiftCardAmount"></span>
                </div>
            </div>
        </nop-nested-setting>
    </div>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.Multimedia.Videos.cshtml
@model ProductModel

<div class="card-body">
    @await Html.PartialAsync("Table", new DataTablesModel
    {
        Name = "productvideos-grid",
        UrlRead = new DataUrl("ProductVideoList", "Product", new RouteValueDictionary { [nameof(Model.ProductVideoSearchModel.ProductId)] = Model.ProductVideoSearchModel.ProductId }),
        UrlDelete = new DataUrl("ProductVideoDelete", "Product", null),
        UrlUpdate = new DataUrl("ProductVideoUpdate", "Product", null),
        Length = Model.ProductVideoSearchModel.PageSize,
        LengthMenu = Model.ProductVideoSearchModel.AvailablePageSizes,
        ColumnCollection = new List<ColumnProperty>
        {
            new ColumnProperty(nameof(ProductVideoModel.Id))
            {
                Title = T("Admin.Catalog.Products.Multimedia.Videos.Fields.Preview").Text,
                Render = new RenderCustom("renderVideosColumnProductVideoUrl")
            },
            new ColumnProperty(nameof(ProductVideoModel.VideoUrl))
            {
                Title = T("Admin.Catalog.Products.Multimedia.Videos.Fields.VideoUrl").Text,
                Width = "400",
                Editable = true,
                EditType = EditType.String
            },
            new ColumnProperty(nameof(ProductVideoModel.DisplayOrder))
            {
                Title = T("Admin.Catalog.Products.Multimedia.Videos.Fields.DisplayOrder").Text,
                Width = "150",
                ClassName = NopColumnClassDefaults.CenterAll,
                Editable = true,
                EditType = EditType.Number
            },
            new ColumnProperty(nameof(ProductVideoModel.Id))
            {
                Title = T("Admin.Common.Edit").Text,
                Width = "200",
                ClassName =  NopColumnClassDefaults.Button,
                Render = new RenderButtonsInlineEdit()
            },
            new ColumnProperty(nameof(ProductVideoModel.Id))
            {
                Title = T("Admin.Common.Delete").Text,
                Width = "100",
                Render = new RenderButtonRemove(T("Admin.Common.Delete").Text),
                ClassName = NopColumnClassDefaults.Button
            }
        }
    })
    <script>
        function renderVideosColumnProductVideoUrl(data, type, row, meta) {
            return '<iframe src="' + row.VideoUrl + '" width="300" /></iframe>';
        }
    </script>
    <div class="card card-default">
        <div class="card-header">
            @T("Admin.Catalog.Products.Multimedia.Videos.AddNew")
        </div>
        <div class="card-body">
            <div class="form-group row">
                <div class="col-md-3">
                    <nop-label asp-for="AddVideoModel.VideoUrl" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="AddVideoModel.VideoUrl" />
                    <span asp-validation-for="AddVideoModel.VideoUrl"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-3">
                    <nop-label asp-for="AddVideoModel.DisplayOrder" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="AddVideoModel.DisplayOrder" />
                    <span asp-validation-for="AddVideoModel.DisplayOrder"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-9 offset-md-3">
                    <button type="button" id="addProductVideo" class="btn btn-primary">@T("Admin.Catalog.Products.Multimedia.Videos.AddButton")</button>
                </div>
            </div>
        </div>
        <script>
            $(function() {
                $('#addProductVideo').click(function () {
                    $('#addProductVideo').attr('disabled', true);
                    var postData = {
                        VideoUrl: $("#@Html.IdFor(model => model.AddVideoModel.VideoUrl)").val(),
                        DisplayOrder: $("#@Html.IdFor(model => model.AddVideoModel.DisplayOrder)").val()
                    };
                    addAntiForgeryToken(postData);
                    
                    $.ajax({
                        cache: false,
                        type: "POST",
                        url: "@Html.Raw(Url.Action("ProductVideoAdd", "Product", new { ProductId = Model.Id}))",
                        data: postData,
                        success: function (data, textStatus, jqXHR) {
                            if (data.success) {
                                //reload grid
                                updateTable('#productvideos-grid');

                                //clear input value
                                $("#@Html.IdFor(model => model.AddVideoModel.VideoUrl)").val('');
                                $("#@Html.IdFor(model => model.AddVideoModel.DisplayOrder)").val('');
                            } else {
                                //display errors if returned
                                display_nop_error(data);
                            }
                        },
                        complete: function (jqXHR, textStatus) {
                            $('#addProductVideo').attr('disabled', false);
                        }
                    });
                });
            });
        </script>
    </div>
</div>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate.Multimedia.cshtml
@model ProductModel

<div class="card-body">
    @if (Model.Id > 0)
    {
		<nop-tabs id="productmultimedia-edit" asp-tab-name-to-select="tab-pictures" asp-render-selected-tab-input="false">
			<nop-tab asp-name="tab-pictures" asp-title="@T("Admin.Catalog.Products.Multimedia.Pictures")" asp-default="true">@await Html.PartialAsync("_CreateOrUpdate.Multimedia.Pictures", Model)</nop-tab>
			<nop-tab asp-name="tab-videos" asp-title="@T("Admin.Catalog.Products.Multimedia.Videos")">@await Html.PartialAsync("_CreateOrUpdate.Multimedia.Videos", Model)</nop-tab>
		</nop-tabs>
    }
    else
    {
        <div class="card card-default">
            <div class="card-body">
                @T("Admin.Catalog.Products.Multimedia.SaveBeforeEdit")
            </div>
        </div>
    }    
</div>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdateProductTag.cshtml
@model ProductTagModel

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

@if (ViewBag.RefreshPage == true)
{
    <script>
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}

 <section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            <div class="cards-group">
                @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ProductTagDetailsTop, additionalData = Model })
                <div class="card card-default card-popup">
                    <div class="card-body">
                        @(await Html.LocalizedEditorAsync<ProductTagModel, ProductTagLocalizedModel>("producttag-localized",
                        @<div>
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    <nop-label asp-for="@Model.Locales[item].Name" />
                                </div>
                                <div class="col-sm-9">
                                    <nop-editor asp-for="@Model.Locales[item].Name" />
                                    <span asp-validation-for="@Model.Locales[item].Name"></span>
                                </div>
                            </div>
                            <input type="hidden" asp-for="@Model.Locales[item].LanguageId" />
                        </div>
        ,
                        @<div>
                            <div class="form-group row">
                                <div class="col-sm-3">
                                    <nop-label asp-for="Name" />
                                </div>
                                <div class="col-sm-9">
                                    <nop-editor asp-for="Name" asp-required="true" />
                                    <span asp-validation-for="Name"></span>
                                </div>
                            </div>
                        </div>
        ))
                    </div>
                </div>
                @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ProductTagDetailsBottom, additionalData = Model })
            </div>
        </div>
    </div>
</section>